version: "3.8"

services:
  web:
    build:
      dockerfile: ./docker/django/Dockerfile
      context: .
    command: sh ./docker/django/local-entrypoint.sh
    volumes:
      - type: bind
        source: .
        target: /code/
    expose:
      - "8000"
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - .env
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    ports:
      - "8443:443"
      - "8442:80"
    depends_on:
      - web
    restart: "${DOCKER_RESTART:-unless-stopped}"
    env_file:
      - .env