# Generated by Django 4.0 on 2021-12-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование в чеке.', max_length=256)),
                ('paymentType', models.FloatField()),
                ('price', models.IntegerField(help_text='Цена за единицу.')),
                ('quantity', models.IntegerField(help_text='Колличество.')),
                ('sum', models.FloatField(help_text='Сумма.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ticket')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
